### ISSUE TITLE
Preserve existing xml tags when re-scraping

### ISSUE THREAD

**Issue by guttedgeek** [sselph/scraper#103]
One issue I have is when I re-scrape my ROMS after a bit of a cleanout. I've tried pulling gamelist.xml down from RetroPie/Recalbox first in an attempt to retain "favorites" and "last played" metadata. Unfortunately the scaper removes this data. Is there someway to refresh only (IE, remove game entries that no longer contain a ROM but otherwise leave extra metadata alone?

Cheers :)

**Comment by sselph** [comment]
I don't have anything to remove entries but I don't think ES will display anything when the rom file can't be found. I have `-refresh` and `-append` but those flags will strip out those values since I'm not even parsing them. Both of them don't remove things from the xml but that was in an effort to not remove things that were manually added. Maybe I could remove things that don't have roms. I can't think of a situation where keeping them would be desired.

**Comment by guttedgeek** [comment]
Unfortunately ES does still display the game if the ROM file doesn't exist (at least on Recalbox). This forces me to rebuild gamelist.xml whenever I have a clean out at which point I loose the existing handwritten entries, last played etc metadata.

Logic (via a switch?) to remove gamelist.xml entries that don't have a corresponding ROM sounds perfect and as you say, I can't think of a scenario where I'd not want to do this.
