### ISSUE TITLE
How to create hash file?

### ISSUE THREAD

**Issue by mxstar1** [sselph/scraper#104]
Im sorry if this is the wrong place to ask, but i have roms that i want to add meta data to the gamelist, however the scraper does not find the hash? aside from manually entering the data to the gamelist, how do i create a file that the scraper will read from? I have all the meta data from another website. What should the format look like? any example? Is there a way to point the scraper to a different website? If there is a better place to ask please let me know where.  Thank you.

**Comment by sselph** [comment]
The hash file is just a csv with
hash,thegamesdb_ID,system_ID,no_intro_name

You can see my csv at https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz

So if you knew there was an entry in thegamesdb you could potentially take the output of using the -missing flag and modify it to add the gamesdb ID to create your own hash.csv

That doesn't sound like what you want. There isn't a way of to point the scraper at a different website since it is matching IDs in thegamesDB and also no good way to use your own metadata using my scraper.

The best I can do is using something like https://github.com/sselph/scraper/wiki/Using-your-own-images with the `-append` flag to add all the images and games for the missing games then edit the metadata with some XML editor. Copying how it is for other games. You have to be careful just directly editing in a text editor (especially windows default text editor) since ' " < > & are all special characters in xml and should be escaped. The windows basic text editor is worse because it will also do some special windows encoding to several characters which breaks things.

You could try asking on https://retropie.org.uk/forum/ or https://www.reddit.com/r/RetroPie/ to see if there are some simple scripts that will convert a csv or some other format in to the xml.
