### ISSUE TITLE
Screenscraper DB Integration 

### ISSUE THREAD

**Issue by Universal-Rom-Tools** [sselph/scraper#106]
Hi SSelph, I'm screech, a moderator on Screenscraper (end the dev of Universal XML Scraper)

Paradadf say us you can be interrested in integrating this new DB to your scraper ;)

(And I read you answer on the other Issue)

This is some information : 

There is 2 API : The SS (ScreenScraper) API and a 100% compatible TGDB API.

We prefer the SS API, based on CRC (like your scraper) to have a good match with game.
If a request ask for an unknown CRC, after 5 request with this CRC, we have a proposal of adding this CRC to the database automatically (with moderation action so it will complete the list of rom per game quickly ;) )
There also an option to request by rom filename (but we don't like it, because, no information about the CRC to fill the database) But you can use it with your corresponding DB (Maybe)

If you have any question about the API (or other, sorry the API Doc is in french for now) don't hesitate to come visit us on IRC ( https://kiwiirc.com/client/irc.freenode.net/#screenzone ) or on the Forum ( http://www.screenzone.fr/forum/viewforum.php?f=434 ) The only thing you need is asking for a DevId (and MarbleMad will give it to you without problem ;) )

hope we can help.

**Comment by sselph** [comment]
Thanks, I joined the IRC but it is pretty early in Rennes so will post here and try and discuss more when we are both awake. The main question I have is do you have things indexed using the no-intro hash? I ask because systems like NES have a header that isn't included in the no-intro hash. Most of the interesting code in my scraper is around determining the correct data in the correct format to hash. That way I get a consistent hash. I also open zip and gzip files and look for the rom inside to get the correct hash, etc.
