### ISSUE TITLE
[Screenscraper API modification] just for your tests

### ISSUE THREAD

**Issue by Universal-Rom-Tools** [sselph/scraper#122]
Hi Sselph,

Screenscraper V2 is near to be release... there is some modification in the API you need to update in your scraper...

This is the new XML comming from the AI V2 : http://s000.tinyupload.com/?file_id=02831958757149867327
Not so much change except for Country / Language shortname.

Now "us" language is "en", and there is much much more media and name possibility (all referenced country)

this is where you can found all the country list (and the short name associated) : http://www.screenscraper.fr/api/regionsListe.php?devid=xxx&devpassword=yyy&softname=zzz&output=xml&ssid=test&sspassword=test

If you have question, don't hesitate....

We don't want you scraper doesn't work anymore with Screenscraper ;) so is we can help you, just ask :D

**Comment by sselph** [comment]
Let me know what the new URL is and when it is expected to go live and will v1 work for some time while people migrate? Or is this a hard cut over?

If the format hasn't changed then switching the region/lang names shouldn't be hard. I was always referring to the lang as en instead of us so that will just be updating what the xml field names are. Adding more regions isn't trivial with the way the xml is laid out. I basically have to describe all the fields I will see so end up with this https://github.com/sselph/scraper/blob/master/ss/ss.go#L41

If there is a v3, you might consider something like the following. It allows to you add regions and languages by just appending a new <info> and describing the xml layout is easy and doesn't change when adding new regions/languages.

```xml
<regionalized_info>
  <info>
    <region>us</region>
    <date>1980-01-01</date>
    <media>
      <media_box2d>http://blah.png</media_box2d>
    </media>
  </info>
  ...
</regionalized_info>
<multilingual_info>
  <info>
    <language>en</language>
    <name>Test</name>
    <synopsis>A test.</synopsis>
  </info>
  ...
</multilingual_info>
```

**Comment by sselph** [comment]
These are the only 2 changes I've noticed. Basically synopsis and genre switched from _us to _en.

```diff
// GameDesc is the desc in many languages.
 type GameDesc struct {
-       EN string `xml:"synopsis_us"`
+       EN string `xml:"synopsis_en"`
        FR string `xml:"synopsis_fr"`
        DE string `xml:"synopsis_de"`
        ES string `xml:"synopsis_es"`

// GameGenre is the genre in many languages.
 type GameGenre struct {
-       EN []string `xml:"genres_us>genre_us"`
+       EN []string `xml:"genres_en>genre_en"`
        FR []string `xml:"genres_fr>genre_fr"`
        DE []string `xml:"genres_de>genre_de"`
        ES []string `xml:"genres_es>genre_es"`
```

**Comment by sselph** [comment]
I did some tests and this seems to be working.
