### ISSUE TITLE
Screenscraper "world" region

### ISSUE THREAD

**Issue by leolobato** [sselph/scraper#131]
I'm trying to scrape only for boxart for neogeo roms and noticed that some would not be downloaded.

Checking the screenscraper page for that game, I can see that there is art only for the "world" region, but not for EN:

http://screenscraper.fr/gameinfos.php?plateforme=142&gameid=37567

I've tried adding "xx" as a region/language when calling the scraper but that didn't seem to work.

Maybe something changed on the API side?

**Comment by Universal-Rom-Tools** [comment]
Hi, I'm actually upgrading NeoGeo on Screenscraper since the new server and new DB is ON.
We also merged AES and MVS (to keep them clean, rom/game are the same on both system ;) )

Don't know how really SSelph Scraper works ;) but normally, Rom country are matching Cover country.

Or you can try "wor" as country for "world"

**Comment by leolobato** [comment]
That might be the parameter that needs to be added to the scraper. Is this new?

**Comment by sselph** [comment]
Sorry I've been working on exporting my library as a C library so it can be added to EmulationStation. Thanks for providing the example. SS changed their API recently and have been cleaning up data. I changed things enough so it wouldn't break but guess I have some more work to do.

**Comment by sselph** [comment]
Let me know if this fixes it.

**Comment by leolobato** [comment]
Awesome, it worked! Thanks!
