### ISSUE TITLE
Add TI-99/4A Support

### ISSUE THREAD

**Issue by TI99er** [sselph/scraper#143]
Hi-

Can support be added for the TI-99/4A emulator?  My understanding is that TI99Sim isn't yet supported because it's an 'experimental package'.  Looking elsewhere here, it seems like a CSV file is needed that lists the sha1 hash, gamesdb ID, and title of each game.  I'd be happy to work on this-  I've already hashed my games and I'm working on adding the ID and title.  

Thanks,
Rich

**Comment by stevetb** [comment]
@sselph could you add support for .CTG files?  CTG Files are used in RetroPie TI-99 Emulation.  I will put together the hash file and TGBD entries for this system.

Also, do you have a direct link for the Master.CSV file for scraper?  The old link I have does not work where I could submit hashes for your approval.

Thank you!

**Comment by sselph** [comment]
I'll add the extension and roll out a big update tonight. The master csv is stored at https://storage.googleapis.com/stevenselph.appspot.com/hash.csv.gz I have a local git repo but don't have it uploaded to github.

**Comment by stevetb** [comment]
Thank you, I will start working on this over the next few days.

**Comment by stevetb** [comment]
Just an update:  I am about 75% done with this.  I should have it done this week.

**Comment by TI99er** [comment]
Thank you!

**Comment by stevetb** [comment]
@TI99er :  I have finished with the hashes, No-Intro type naming convention, and created all of the art for everything on TGDB.  I have uploaded these and placed the hashes into the missing hashes issue on this site for SSELPH to upload.  Once he uploads I am sure I will have a few changes to make.

Please help me review too once uploaded and we can add any titles which I have missed.  It is so hard to pull in information from a lot of these since there is only a small group of people still active in the community.  If you are one of those that is active in the community I REALLY would love to connect and see if you can help me make this set even better.

Check out TGDB for now and help me add any descriptions & metadata I have missed.  

-Steve

**Comment by stevetb** [comment]
@sselph - Thank you, it looks perfect.  I will complete the TGDB information now but the Scraper information is 100%.  Thank you for adding it all so quickly!

Please close this issue

**Comment by TI99er** [comment]
Thank you to both of you!  I ran the scraper, and it looks great!  

@stevetb -  I'll be glad to help you out with this set.  By that, you mean adding/updating at the gamesdb.net, right?  I currently run 2 TI99 sites:  99er.net and ti99db.org.  You're welcome to use any of the images and information from either site.  There's a pretty active TI community at ti99.atariage.com - I'm not sure if you ever check in on there.  Thanks again, and I'll take a look at thegamesdb.net.

-Rich
