### ISSUE TITLE
Feature Request: <video> and <marquee>

### ISSUE THREAD

**Issue by alaindesjardins** [sselph/scraper#146]
This is just a request.  Is it possible to add option to generate <video> and <marquee> using our own data?  I just finally found the tool I've been looking for to generate my gamelist.xml files using metadata and my own boxart and it would be great to extend that functionality with the suggestions below.

Options could be something like, -video_path="./snaps" and -marquee_path="./wheel" which would result in adding as an example:

<video>./snaps/2020 Super Baseball (USA).mp4</video>
<marquee>./wheel/2020 Super Baseball (USA).png</marquee>

I suppose it would need another option for the file extension to go along with it and possibly suffix. like:
-video_suffix="-video"
-marquee_suffix="-marquee"
-video_format="mp4"
-marquee_format="png"

Option to append the data to an already scraped gamelist.xml would most likely top it off.

Love your scraper by the way!  THANK YOU!

**Comment by pjft** [comment]
+1!

**Comment by robertybob** [comment]
@sselph I think either @fieldofcows or @jdrassa would be good people to ask about Emulationstation video stuff :)

**Comment by pjft** [comment]
Thanks for picking this up!

The marquee should have a max size similar to the other images we scrape,
but bound horizontally (as they're usually wide). The max size is just to
keep them manageable in ES memory.

As for videos, MP4 is usually the most common format that you'll get in
EmuMovies and other places, though anything that VLC can play (since that's
the default player, and OMXPlayer plays even more formats) would work.

For the Pi, though, if it's an option your sources provide, VLC doesn't
cope well with anything that has more quality than 480x360@30fps, for
reference. I don't expect you to transcode anything in Go, though, but if
the source allows you to choose anything, at least you have a guideline :)

Let me know if these help, or how can I clarify things further.

Thanks.




- Paulo Tavares

**Comment by sselph** [comment]
Sounds good. I'll add a default of 400px width for the marquee and add some common extensions for the video when searching locally to see if the user already has one downloaded. I was in the middle of testing but seems like ScreenScraper.fr is down so this may have to wait another day.
