### ISSUE TITLE
Question: How do I scrape scummvm?

### ISSUE THREAD

**Issue by adabo** [sselph/scraper#162]
I have a working scummvm set, but non of them are found by the scraper. I've tried all three sources. Any ideas? What scummvm rom set was used?

**Comment by sselph** [comment]
It has been a while since I've looked at the scummvm stuff. Looking at the code, it looks for files named *.svm then takes the name and looks it up in a set of names I pulled out of the scummvm source at the time. The only source I'm using is thegamesdb. This was all based on what I was observing in retropie so maybe it is specific to that implementation.

The list of games is in sheet2 here:
https://docs.google.com/spreadsheets/d/1HUj7nnDsJU2kpB_pFkzzHbO8rpwsdLQivZtHbPO3xTE/edit#gid=1414861348

**Comment by adabo** [comment]
Thank you.

**Comment by paradadf** [comment]
You can scrape scummvm using ScreenScraper database and sselph's scraper like this:
https://forum.recalbox.com/topic/3832/filelist-scrapping-scummvm/

The trick is to add the game's full name inside the game's launcher (.scummvm for recalbox, .svm for retropie). That laucher only has to have the gull name inside in order to match the sha1, otherwise it won't find anything.

**Comment by adabo** [comment]
Nice! Thank you.
