### ISSUE TITLE
Add Dreamcast support

### ISSUE THREAD

**Issue by karl0ss** [sselph/scraper#34]
As Dreamcast is pretty much working now on RPi2 with RetroPie, any chance this can be updated to include Dreamcast support?

**Comment by karl0ss** [comment]
I see in other threads you need hashes? if you tell me how I can get them I will try and create a csv for you?

**Comment by robertybob** [comment]
@karl0ss Just out of interest, which are the DreamCast games (that you're playing) that work really well? Is Reicast working better than the N64 emulators?

Having had a quick look over at TheGamesDB, there is quite a lot of info missing from their 300 Dreamcast games:
http://thegamesdb.net/browse/16/?sortBy=g.GameTitle&limit=100&searchview=table

Do you have an account on that website and would you fill in the missing info? I only ask because I would have done it myself, however once myself and @sselph complete PSX the chances are I'll volunteer to update the info on those particular games (which I fear may be in the hundreds).

**Comment by sselph** [comment]
I can't make promises but I will look in to it. I have the hashes from redump for gdi/bin which, without any research, looks similar to cue/bin that psx uses so that is good. The issue with redump is that clones aren't called out so if a game has a different title in the US and Japan I might miss the Japan version if it isn't named the same.

@robertybob I seem 561 games in redump but there is no telling how many may be clones so 300 sounds like a good start.

**Comment by karl0ss** [comment]
@robertybob I've been playing Virtua Tenis/Shenmue and a few others, if you look at this post - http://blog.petrockblock.com/forums/topic/configuring-controllers-in-reicast/ there has been good progress made on the emulator, I have an account on TheGamesDB and if you give me the hashes or what is missing (or tell me how to get) I will more than happily update the information for you guys.

**Comment by sselph** [comment]
https://docs.google.com/spreadsheets/d/1rrXIvS1OijhdabPuyDkHd4nzb2y0qfbrbXdqGfzWDEw/edit#gid=988131021

This is my work in progress. Feel free to request permission to edit. I have some scripts and Vlookups to match most the games by name to the name in tgdb. I now go through and look at all tgdb games to make sure they all match a game in the redump DB.

**Comment by robertybob** [comment]
This looks great! Is there a reason some cells are red and others green? At first I assumed it was because there wasn't a corresponding entry on TGDB but now I'm not so sure.
 
I checked a few of the links and they match up to the correct games, so as it seems to work ok maybe @karl0ss (and at a later date myself) fill in the missing Release Dates / Developer / Publisher information ?

**Comment by karl0ss** [comment]
Yeah, if you let me know what you need me to do to get dreamcast scraping working, I will do what I can to help :)

**Comment by sselph** [comment]
This is me matching entries in redump to entries in tgdb I start by formatting the names in similar ways to find matches which gets most of them but there is some manual work. So the left tab is redump the right is tgdb. On redump red means I haven't matched it to a tgdb entry yet. Green means it has been matched. On tgdb tab red means that it hasn't been matched to a redump entry yet, green means it has. 

So I'm going through every tgdb entry and trying to make sure it is green by pasting the name in to all the column Ds in redump that match it. I usually match all but a few(1-2%) of these since there are some homebrew games listed and the no-intro/redump db's aren't 100%. Once that is done I'll go through the redump side since clones aren't called out german versions of us games will have the same title just written in german, etc so I'll attempt to fix those.

After that the redump side will show all the games that aren't in tgdb and that is where you normally add the missing entries.

**Comment by robertybob** [comment]
I think I understand now! So to make every tgdb entry green, we would be to hash the ROMs ourselves.. and to make every redump green we need to create an entry in tgdb ?

Could you tell me how I get permisison to ammend the spread sheet? Otherwise I'm more than happy to post stuff here:

aerowings 2 airstrike - 19317
Alienfront Online - 2411
Buggy Heat - 11073
Caesars Palace 2000: Millennium Gold Edition - 29222

**Comment by sselph** [comment]
Not quite, all it takes right now is to copy and paste the name in tgdb tab in to the redump tab to mark that it matches. It is usually something like redump says might & magic and tgdb says might and magic so you edit the redump side to match the tgdb side then things turn green. To get access you should be able to sign in and click the share icon and request an invite.

**Comment by robertybob** [comment]
Ah right, found it, but It's asking me for your email address

**Comment by sselph** [comment]
Ah it is on my page here steven.selph@gmail.com

**Comment by robertybob** [comment]
The Redump tab is complete for all games except Japanese and non English language (French, German etc.).

In the TGDB tab I believe the vast majority of the red cells are technically duplicates - European releases of games which already have an entry for their US counterpart (whether that has the identical name or not).

**Comment by sselph** [comment]
Thanks! I'll work on adding the gdi/bin support to make use of these.

**Comment by sselph** [comment]
I added gdi/bin support but appears that the es_systems.cfg may be set to only use cdi. So may need the hashes for cdi images too. @karl0ss if you have a somewhat complete set of games that you are sure are good and named correctly you can send me the hashes.

On Linux:
```bash
$ cd path/to/roms
$ shasum *.cdi > hashes.shasum
```

It will take a while since the images are typically large but when it completes you can email me the hashes.shasum file.

**Comment by karl0ss** [comment]
Hey sselph.

I will get on and do that tonight for you, I have a pretty much complete set.

**Comment by robertybob** [comment]
@karl0ss Hey. Did you ever do this?

**Comment by robertybob** [comment]
I have no idea what stage this got to, nor do I know how good emulation is on the Pi now and the foreseeable future, but I'm happy to assist.

**Comment by sselph** [comment]
I added DC support. I was waiting to see if I could get the other format hashes instead of just gdi but I can close this.
