### ISSUE TITLE
Add scummvm support

### ISSUE THREAD

**Issue by J-Swift** [sselph/scraper#37]
To start... thanks for the tool, it works great!

And to jump on the bandwagon of asking for additional platform support... are there any plans on scummvm?

**Comment by robertybob** [comment]
I can't speak for @sselph , but I would assume someone would have to compile a definitive list of scummvm-compatible games from the 'PC' section of thegamesdb.net to scrape against (seeing as scummvm is not a platform but an emulator of specific PC games).

**Comment by sselph** [comment]
I haven't used scummvm before, haven't really heard of it before this issue so have no clue how things are structured and it seems unlike most of the other emulators in ES. So I have lots of questions.

In the scumm source code they have hashes that map to the names of the games so that data is there. Also scummvm contains several engines and one of the many engines is scumm is this the main engine being used or would I need to extract all the engines hash data?

I am going by what I see in retropie but ES loads .sh and .svm files but the games are elsewhere so I don't know how I'd determine what game data goes with what .svm. Reading the RetroPie wiki it seems like the .svm files are generated by scummvm after some import process. Are the svms something that could be parsed? Internally to scumm they have a set of short names so if that short name could be extracted from the svm, I could bypass all the hashing of game data and trying to find game data since scumm already does that to determine the short name.

This is the example of the data I extracted:
https://docs.google.com/spreadsheets/d/1HUj7nnDsJU2kpB_pFkzzHbO8rpwsdLQivZtHbPO3xTE/edit?usp=sharing

**Comment by HerbFargus** [comment]
I'm not super familiar with your tool- its next on my list of things to test, but as an avid scummvm fan (I wrote most of the wiki on it)  you seem to have it spot on- the .svm files are created  based on these data files: http://wiki.scummvm.org/index.php/Datafiles.  as you detailed in your google doc. The video on the wiki page shows how the .svm files are generated- the svm files generated equivocate to the datafiles added as far as their file name goes but scraping wise they would match the long name. 

I'm pretty sure scumm is the main engine (at least for the games I play on it) The other most popular would be the sci engine http://wiki.scummvm.org/index.php/Engines but I don't know how that would affect scraping (if at all)  I'm happy to test things and help with anything you might need.

**Comment by sselph** [comment]
@HerbFargus 
Thanks. I think I have enough to start. The game list across all engines is very small so I'll just make a mapping of gameid to entries in TGDB if it exists. I'm in the middle of refactoring the code so after that is done I should be able to add the stuff for scraping scummvm in.

Can you confirm that the svm files in the roms directory are named balloon.svm, baseball.svm, basketball.svm, etc?

Also if anyone has free time feel free to continue adding in the IDs for the games in the sheet.

**Comment by HerbFargus** [comment]
I'm adding my scummvm files right now to verify the svm files. I'm pretty sure they match the data files. I'm working on your chart right now as well.

**Comment by J-Swift** [comment]
I can put some time into this as well seeing as I submitted the ticket.

@HerbFargus Do you know if the .svm files equate to a particular version of a game (e.g. apple II version can be distinguished from DOS version)? If so, then there would be quite a bit more work in terms of mapping each .svm to its versions. It would also require more work bringing TGDB platform support up to par with the platforms supported by scummvm.

**Comment by HerbFargus** [comment]
I've done almost all of the humongous entertainment games on thegamesdb already minus a few obscure ones here and there I'll try and add the missing ones as well at some point. I'm not sure how the .svm files handle different versions. for games like backyard sports there are 3 or 4 different versions based off the year but I think that the data files are also different too so that would make the svm different.

**Comment by sselph** [comment]
I didn't notice that before but seems the gameid can reference the same game on different platforms
example maniac(Maniac Mansion) is on Apple II, C64, DOS, Amiga, Atari. So we can just choose the PC entry for it and call it a day or I can try and write a more elaborate scraper, seeing if the svm file can be read and then use that to see if it contains platform information or the list of files and then hash those to determine the game/platform combination to get the correct ID.

**Comment by HerbFargus** [comment]
yeah i just realised that- the svm is equivalent to the gameid but the game id will vary by platform depending on the source of your files so for example my file for freddi fish 2 is `freddi2` but the svm file created is freddi2-win. I think selecting pc would be the simplest route.

**Comment by J-Swift** [comment]
@sselph Right, that's what I was getting at above. I have a basic scraper for the supported platforms broken down by game, as [provided here](http://scummvm.org/compatibility/). You can find the output from a runthrough here:
https://docs.google.com/spreadsheets/d/1Ypua9vwLzvJy24z4XObpvgf0XZcytBNC7ZISrxihzo4/edit?usp=sharing

I just pulled the PC game id for all games when editing your sheet. Like I said, if we wanted to add entries for each variant, TGDB would need to have a lot of those platforms/entries added on their end first before we could match them up.

**Comment by sselph** [comment]
I added all the entries that were in the sheet. Feel free to let me know when the DB has more games and I can update my DB.

**Comment by HerbFargus** [comment]
I added all the living books series to thegamesdb and updated the spreadsheet- along with a few more humongous entertainment games.

**Comment by sselph** [comment]
Thanks. I've added these in.
