### ISSUE TITLE
Feature Request - scrap Intellivision games (.int)

### ISSUE THREAD

**Issue by dcteal** [sselph/scraper#58]

**Comment by sselph** [comment]
Support has been added for the extension .int. There are no hashes for this in no-intro but @stevetb volunteered to provide some hashes.

**Comment by stevetb** [comment]
@sselph I should have this done soon.  I will start working on this tonight.  Since we do not have a No-Intro set to pull from I will pull what I have and work off of that.

**Comment by stevetb** [comment]
@sselph TGDB was dead slow tonight.  Will finish this tomorrow night, so close too.

**Comment by stevetb** [comment]
@sselph As promised, here is the .CSV for all Intellivision ROMs I could find.  6 of these games I could not find corresponding ROMs, but they exist so I kept them in the list.  I am sure there are other homebrew titles, and possibly a few other official titles, but this should cover most.  Since there is not a No-Intro Romset, this was the best I could do.  Please let me know if I made any errors and need to correct.  I stripped off all Company, Year, Extensions, and the weird versioning ( such as [!] or [b1] or [h1]).

https://drive.google.com/open?id=1NF9ILTmUct0y_AvvCbj4_EHpmHyFuky5hk71hHbyIW8

**Comment by sselph** [comment]
Done

**Comment by stevetb** [comment]
This looks great!  Thank you.

@sselph can you close this?
