### ISSUE TITLE
subfolder

### ISSUE THREAD

**Issue by partyguy2016** [sselph/scraper#60]
hello, 

i'm having trouble using the scraper in subfolders.  For instance nes/romset/A-C. I ran the scraper in the A-C folder, it generated an image folder and a .xml file but the information isn't showing up on the retropie screen after reboot. Please let me know if there is a way to make this work.  Thanks

**Comment by sselph** [comment]
I'm sorry. I meant to respond earlier but my laptop was hijacked a one year old.

ES expects a single gamelist xml for the system, Since you are running scraper in each sub folder you are creating multiple gamelists. If you run the scraper in the parent folder it supposedly works. All roms I've tested have been in one folder but others have run this with subfolders and have said it works.

**Comment by partyguy2016** [comment]
Thank you. It works perfectly.
