### ISSUE TITLE
Boot time

### ISSUE THREAD

**Issue by j08rebelo** [sselph/scraper#63]
After using the scraper for a few thousand roms (NES, SNES, Megadrive, GB, N64...) i notice EmulationStation takes a huge amount of time to boot. Without the thumbnails and description it usually took a few seconds, now it goes for about 5 minutes. 

Is there a way to make it faster?

**Comment by sselph** [comment]
I've heard that using different themes can help with some crashing issues so you can try that. The issue is that ES has to read and parse all the XML files. This could be causing it to take too much time. Aloshi was in the process of switching to using a DB to help fix that.

If a theme change doesn't help, I can try adding a feature to truncate extra long descriptions maybe that could reduce the time to parse if you are ending up with extra large XML files.

**Comment by j08rebelo** [comment]
That would be a great idea. If you could work on that solution would be
fantastic.
Em 29/01/2016 17:13, "Steven Selph" <notifications@github.com> escreveu:

**Comment by sselph** [comment]
I added a flag -overview_len that can be passed a number. It will limit the length of the description to that number plus an ellipsis so you can set this to something reasonable that fits on the screen so maybe it will reduce the amount of data that has to be parsed.

I don't know if it will help but thats about all I can think of that I can do from my side.

**Comment by j08rebelo** [comment]
Thank you. I don't understand a lot about coding. So I need do download and
unzip the scraper again and set those parameters?
Em 30/01/2016 03:40, "Steven Selph" <notifications@github.com> escreveu:

**Comment by sselph** [comment]
yeah
