### ISSUE TITLE
no version number when building from git HEAD

### ISSUE THREAD

**Issue by joolswills** [sselph/scraper#69]
the -version parameter seems to return nothing when building from git - I am just switching the scraper module in retropie to build from source on jessie+ so it also works on x86. for now I will display "unknown" as the version, but perhaps it could include a v1.5-dev or git revision or something?

**Comment by joolswills** [comment]
It might be better if I make it only build from stable releases - will look into that

**Comment by joolswills** [comment]
"go get" doesn't seem to allow me to get a specific tag - is there a way to build from a git clone or would that not handle go dependencies etc ?

**Comment by sselph** [comment]
The version variable is set from the build command. My release process is to run a script where I pass the next version number and it creates the tag, cross compiles all the different versions, and uploads them. You can set this variable with `go build -ldflags "-X main.versionStr=my_version" github.com/sselph/scraper` If it will help, I can display a known string when the binary wasn't build with this parameter..

go get will do a git clone for the scraper and all its dependencies at HEAD in to $GOPATH. I normally keep the master's HEAD in a working state but it might be possible to do something like:
```
go get -u -d github.com/sselph/scraper
cd $GOPATH/src/github.com/sselph/scraper
git checkout tags/v1.0.10
go build(or install) github.com/sselph/scraper
```

it might be required to run another `go get -d github.com/sselph/scraper` after switching the git repo since if I remove a dependency it wouldn't be fetched by the original get.

**Comment by joolswills** [comment]
thanks - if HEAD is going to be stable, I'm happy to leave it as is - I currently display v(Git) for version, but I could look at using the last tag+commit revision or so. Thanks for the info. I will close this.
