### ISSUE TITLE
Feature request: scrap by name

### ISSUE THREAD

**Issue by daaa57150** [sselph/scraper#81]
Hi,

This scrapper really helped me a lot with my "basic" roms, but for roms with translation patches applied, this is of no use... It would be nice to have the option to use the name of the file instead of the hash.

**Comment by sselph** [comment]
I have https://github.com/sselph/scraper/issues/13 where I was thinking about writing something to allow you to search for games that didn't match but never got to it. I had a prototype, but never got it cleaned up. I don't think I want to make any kind of name based auto scraping for console roms since it may be error prone.

If you need this in a timely manner, I would suggest seeing if there are some other scrapers out there that work based on name and seeing if they can be instructed to only act on entries that are missing after running this scraper.

**Comment by daaa57150** [comment]
I looked for other scrapers but didn't find any; so I thought about installing emulation station and using the internal one but it doesn't install on a mac...

I effectively need this in a timely manner, it's just that right now I have like 30 roms and I don't want to do it by hand :). I guess I'll program a quick and dirty scrapper myself.

Thanks for the answer.
