### ISSUE TITLE
Fetch everything except images

### ISSUE THREAD

**Issue by robertybob** [sselph/scraper#9]
Hi!
I wondered whether it would be possible to only scrape descriptions/release dates etc and not images. 

Basically, I have all my roms named with corresponding boxart images and I want to be able to create a gamelist.xml using those existing images but with game descrptions etc scraped from thegamesdb.net . Is this possible or something which could be possibly be included in a future release? Perhaps the scraper could skip downloading an image if one is found in the directory?

**Comment by sselph** [comment]
The current logic will have it skip downloading the image if there is already an image in the location where it was going to save the image. So if there is a rom file named rom_file.bin it will attempt to download images/rom_file.jpg images/rom_file-thumb.jpg if they exist it will skip it and you will see "INFO: Skipping: images/rom_file.jpg". If using -thumb_only it will only attempt to get the images/rom_file-thumb.jpg file.

**Comment by robertybob** [comment]
Thanks, I'll give it a go :)

**Comment by robertybob** [comment]
Hi ,

I've put my roms in one folder and the boxart images in /images, yet when I run the scraper it still creates rom-image.jpg and rom-thumb.jpg files and the gamelist.xml links to those new images, not the ones I originally had in the folder. 

E.G SMB.nes in rom folder, SMB.jpg in /images folder - scraper creates SMB-image.jpg and SMB-thumb.jpg.

Am I doing something wrong still?

**Comment by sselph** [comment]
Ah no I told you the wrong instructions. Sorry for the confusion. The files it expects are SMB-image.jpg and SMB-thumb.jpg. A quick fix would be to cd to the image folder and do something like:
```bash
$ cd ~/RetroPie/roms/snes/images
$ rename 's/^(.*)\.jpg$/$1-thumb.jpg/' *.jpg
$ cd ..
$ scraper -thumb_only
```
This will rename all the files to include the -thumb.jpg and then tell the script to ignore the -image.jpg files and use the -thumb image for both. The thumbnails are not actually used so it is okay if the images aren't actually thumbnail sized.  I have just been including them there because the format allowed it and I figured Emulation Station would eventually do something with them. I'll also add a -no_thumb option to do the opposite and only get the -image version of the files and not write the thumbnail to the xml.

**Comment by robertybob** [comment]
Many thanks for your reply :) I used a Windows build if your scraper if that makes any difference?
